export const DOCUMENT_EDIT = 'DOCUMENT_EDIT';

export const DOCUMENT_FETCH_REQUEST = 'DOCUMENT_FETCH_REQUEST';
export const DOCUMENT_FETCH_SUCCESS = 'DOCUMENT_FETCH_SUCCESS';
export const DOCUMENT_FETCH_ERROR = 'DOCUMENT_FETCH_ERROR';

export const DOCUMENT_POST_REQUEST = 'DOCUMENT_POST_REQUEST';
export const DOCUMENT_POST_SUCCESS = 'DOCUMENT_POST_SUCCESS';
export const DOCUMENT_POST_ERROR = 'DOCUMENT_POST_ERROR';

export const DOCUMENT_IDENTIFY = 'DOCUMENT_IDENTIFY';

export const DOCUMENT_POST_VALIDATION_ERROR = 'DOCUMENT_POST_VALIDATION_ERROR';
